### ISSUE TITLE
Review-footer-section

### ISSUE THREAD

**Issue by aeh1707** [stephnna/portfolio#5]
Leave your feedback about the footer section

**Comment by aeh1707** [comment]
You should remove the labels from the form because there are no actual labels to connect with your form inputs.

**Comment by Abdo9826** [comment]
Everything in his place , I don't have anything to say

**Comment by aeh1707** [comment]
You should set the border for the input in green color as it is on the figma design.

**Comment by gasangw** [comment]
He should specify the content in the placeholder for example instead of "placeholder=Full name" he would have used "placeholder=Thomas Gasangwa" this simplifies work for those filling in the form.
